### ISSUE TITLE
webcam_demo.py can't streaming

### ISSUE THREAD

**Issue by jacky1031** [WXinlong/SOLO#115]
I want to streaming webcam with default camera or a usb camera or a mp4 file.

when I use webcam_demo.py

ubuntu command line 

python webcam_demo.py ../configs/solo/decoupled_solo_light_r50_fpn_8gpu_3x.py ../checkpoints/DECOUPLED_SOLO_LIGHT_R50_3x.pth

but the error message 

ECOUPLED_SOLO_LIGHT_R50_3x.pth
<VideoCapture 0x7f31a7166070>
Press "Esc", "q" or "Q" to exit.
/home/jackytsai/anaconda3/envs/solo/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "webcam_demo.py", line 47, in <module>
    main()
  File "webcam_demo.py", line 43, in main
    img, result, model.CLASSES, score_thr=args.score_thr, wait_time=1)
  File "/home/jackytsai/SOLO/mmdet/apis/inference.py", line 155, in show_result
    for i, bbox in enumerate(bbox_result)
  File "/home/jackytsai/SOLO/mmdet/apis/inference.py", line 155, in <listcomp>
    for i, bbox in enumerate(bbox_result)
AttributeError: 'tuple' object has no attribute 'shape'

I can use "inference_demo.py" successful and dump a instance segmentation picture

any help with this issue?

thanks

**Comment by shmilywh** [comment]
i had met the same issue, any help with this issue? thanks a lot

**Comment by chenxyyy** [comment]
Use this code for webcam_demo


```
from mmdet.apis import init_detector, inference_detector, show_result_pyplot, show_result_ins
import mmcv
import cv2

def main():
    config_file = '/home/user/Documents/SOLO-master/configs/solov2/solov2_x101_dcn_fpn_8gpu_3x.py'
    checkpoint_file = '/home/user/Documents/SOLO-master/checkpoints/SOLOv2_X101_DCN_3x.pth'
    video_path = "/home/user/Documents/data/20201029124559/20201029124559_Channel1.avi"
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
    camera = cv2.VideoCapture(video_path)

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    fps = camera.get(cv2.CAP_PROP_FPS)
    frame_width = int(camera.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(camera.get(cv2.CAP_PROP_FRAME_HEIGHT))
    out = cv2.VideoWriter('output.avi', fourcc, fps, (frame_width, frame_height))

    while True:
        ret_val, img = camera.read()
        result = inference_detector(model, img)
        img = show_result_ins(img, result, model.CLASSES, score_thr=0.25)
        # img = cv2.resize(img, (1080, 720))
        out.write(img)
        # cv2.imshow('solo', img)
        # if cv2.waitKey(1) & 0xFF == ord('q'):
        #     break
    camera.release()
    out.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
```
