### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by YourMint** [WXinlong/SOLO#139]
Running setup.py develop for mmdet
    Running command /home/mint/anaconda3/envs/solo/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mint/SOLO-master/setup.py'"'"'; __file__='"'"'/home/mint/SOLO-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    building 'mmdet.ops.nms.nms_cuda' extension
    gcc -pthread -B /home/mint/anaconda3/envs/solo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include -I/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/TH -I/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/mint/anaconda3/envs/solo/include/python3.7m -c mmdet/ops/nms/src/nms_cuda.cpp -o build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from mmdet/ops/nms/src/nms_cuda.cpp:2:
    /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)

    mmdet/ops/nms/src/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
    mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                           ^
    mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^~~~~~~~~~
    In file included from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                     from /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from mmdet/ops/nms/src/nms_cuda.cpp:2:
    /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:277:30: note: declared here
       DeprecatedTypeProperties & type() const {
                                  ^~~~
    mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^~~~~~~~~~
    mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^~~~~~~~~~
    /home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: command 'gcc' failed with exit status 1
ERROR: Command errored out with exit status 1: /home/mint/anaconda3/envs/solo/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mint/SOLO-master/setup.py'"'"'; __file__='"'"'/home/mint/SOLO-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 403, in run
    pycompile=options.compile,
  File "/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 802, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/mint/anaconda3/envs/solo/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/mint/anaconda3/envs/solo/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mint/SOLO-master/setup.py'"'"'; __file__='"'"'/home/mint/SOLO-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-63d2btq_'

This error took me too much time,but I cat't solve it.
my envs:
CUDA:11.1
cuDNN:8.0.4.30
pytorch:1.7.1
torchvision:0.8.2

**Comment by YourMint** [comment]
my GPU is RTX3070

**Comment by cwlinghk** [comment]
I met the same error also with RTX 3070

**Comment by DavideDaz** [comment]
Hello, any update on this troubleshooting?

**Comment by zhuaiyi** [comment]
Take a try by changing all "AT_CHECK" to "TORCH_CHECK". It works with my RTX3070.
