### ISSUE TITLE
how to compile cuda file

### ISSUE THREAD

**Issue by lushaoan** [WXinlong/SOLO#152]
how to compile .cpp and .cu file in mmdet/ops/

I got this error when i running test_ins_vis.py

Traceback (most recent call last):
  File "tools/test_ins_vis.py", line 15, in <module>
    from mmdet.core import coco_eval, results2json, wrap_fp16_model, tensor2imgs, get_classes
  File "/media/lsa/MobileDisk3/paper/mechine learning/instance segmentation/solo/SOLO/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/media/lsa/MobileDisk3/paper/mechine learning/instance segmentation/solo/SOLO/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/media/lsa/MobileDisk3/paper/mechine learning/instance segmentation/solo/SOLO/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/media/lsa/MobileDisk3/paper/mechine learning/instance segmentation/solo/SOLO/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/media/lsa/MobileDisk3/paper/mechine learning/instance segmentation/solo/SOLO/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/media/lsa/MobileDisk3/paper/mechine learning/instance segmentation/solo/SOLO/mmdet/ops/dcn/deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'

**Comment by kexinhandsome** [comment]
i have this problem, too.
have you solved this error?how?
