### ISSUE TITLE
if 'caption' in anns[0]: IndexError: list index out of range

### ISSUE THREAD

**Issue by huangshouyou** [WXinlong/SOLO#169]
Thanks for your error report and we appreciate it a lot.

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 18/18, 19.6 task/s, elapsed: 1s, ETA:     0s
writing results to results_solo.pkl
Starting evaluate segm
Loading and preparing results...
Traceback (most recent call last):
  File "tools/test_ins.py", line 257, in <module>
    main()
  File "tools/test_ins.py", line 235, in main
    coco_eval(result_files, eval_types, dataset.coco)
  File "/home/atm/hsyou/SOLO/mmdet/core/evaluation/coco_utils.py", line 41, in coco_eval
    coco_dets = coco.loadRes(result_file)
  File "/home/atm/anaconda3/envs/solo/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 326, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by zhuaiyi** [comment]
I have met the same problem.
Unsolved yet.

**Comment by gernophil** [comment]
Any solutions on this yet? Having the same error? Seems to be related to the bbox annotations, but I wasn't able to rule this error out yet.

**Comment by onepiece010938** [comment]
same problem QQ

**Comment by jiangxinhao2020** [comment]
Has anyone solved the problem?

**Comment by songyangsun** [comment]
if you use coco format, please check class. then you should confirm the path you train,i make a mistake on training path.

**Comment by renxingaming** [comment]
i have met the same problems. how can solve this problem?

**Comment by jiubie12** [comment]
> 我遇到了同样的问题。如何解决这个问题？我今天解决了这个问题！如果遇到同样的问题，可以尝试调整训练参数来再次训练模型，因为之前的模型无法训练。

请问，怎样调整训练参数呢？

**Comment by renxingaming** [comment]
出现这个问题是因为测试集中某张图像没有目标被分割出。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WXinlong/SOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月22日(星期六) 晚上11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WXinlong/SOLO] if 'caption' in anns[0]: IndexError: list index out of range (#169)





  
我遇到了同样的问题。如何解决这个问题？我今天解决了这个问题！如果遇到同样的问题，可以尝试调整训练参数来再次训练模型，因为之前的模型无法训练。
  
请问，怎样调整训练参数呢？

**Comment by yunhuiming** [comment]
那如果测试集中某张图片的确没有目标怎么办
