### ISSUE TITLE
RuntimeError: There were no tensor arguments to this function

### ISSUE THREAD

**Issue by DongGuangchang** [WXinlong/SOLO#218]
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/home/dy/dong/instanceSegmentation/SOLO-master/mmdet/apis/train.py", line 111, in train_detector
    timestamp=timestamp)
  File "/home/dy/dong/instanceSegmentation/SOLO-master/mmdet/apis/train.py", line 297, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/dy/software/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dy/software/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 268, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/dy/dong/instanceSegmentation/SOLO-master/mmdet/apis/train.py", line 78, in batch_processor
    losses = model(**data)
  File "/home/dy/software/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dy/software/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/dy/software/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dy/dong/instanceSegmentation/SOLO-master/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/dy/dong/instanceSegmentation/SOLO-master/mmdet/models/detectors/base.py", line 142, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/dy/dong/instanceSegmentation/SOLO-master/mmdet/models/detectors/single_stage_ins.py", line 78, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/dy/dong/instanceSegmentation/SOLO-master/mmdet/models/anchor_heads/solov2_head.py", line 249, in loss
    loss_ins = torch.cat(loss_ins).mean()
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]

I encountered a problem during training. How can I solve it? thanks！

**Comment by biendltb** [comment]
I hit the same issue. The problem is that there were empty predictions from the model for that batch which returns an empty list of losses. Not sure how this could be solved.
