### ISSUE TITLE
TypeError: SOLOv2: __init__() got an unexpected keyword argument 'mask_feat_head'

### ISSUE THREAD

**Issue by ZHANGH83** [WXinlong/SOLO#235]
I want to try a simple training on my own datasets, but got this error, how to solve it, please?

___Traceback (most recent call last):
  File "c:\users\echo\mmcv\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'mask_feat_head'

During handling of the above exception, another exception occurred:_

_Traceback (most recent call last):
  File "E:\DeepLearning\Pytorch\Projects\SOLO-master\SOLO-master\tools\train.py", line 127, in <module>
    main()
  File "E:\DeepLearning\Pytorch\Projects\SOLO-master\SOLO-master\tools\train.py", line 100, in main
    model = build_detector(
  File "D:\Anaconda\Anaconda3\envs\mmlab\lib\site-packages\mmdet\models\builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "c:\users\echo\mmcv\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "c:\users\echo\mmcv\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "c:\users\echo\mmcv\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SOLOv2: __init__() got an unexpected keyword argument 'mask_feat_head'___

**Comment by Coisini-Tinkle** [comment]
I have encountered with the same problem .How to solve it? Please.

**Comment by hsuan1996** [comment]
Did you solved this problem?
