### ISSUE TITLE
OSError: ../checkpoints/DECOUPLED_SOLO_R50_3x.pth is not a checkpoint file

### ISSUE THREAD

**Issue by Chen823** [WXinlong/SOLO#36]
an oserror occurred when i run "python inference_demo.py":
Traceback (most recent call last):
  File "inference_demo.py", line 12, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "/home/adt/Documents/alg/big-xing/SOLO/mmdet/apis/inference.py", line 38, in init_detector
    checkpoint = load_checkpoint(model, checkpoint)
  File "/home/adt/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 168, in load_checkpoint
    raise IOError('{} is not a checkpoint file'.format(filename))
OSError: ../checkpoints/DECOUPLED_SOLO_R50_3x.pth is not a checkpoint file

**Comment by Chen823** [comment]
it works after modify the file path
