### ISSUE TITLE
RuntimeError: "sum_cuda" not implemented for 'Bool'

### ISSUE THREAD

**Issue by Womcos** [WXinlong/SOLO#73]
We implement the latest code SOLO_v2 for training and get one error. We follow the installation and dataset preparation process for coco dataset. Our environments are as bellows:
GPU: GTX 1080 Ti 
python: 3.6
cuda: 9.0
pytorch: 1.1.0
We can regularly run the test code and get the results accroding to the repository. However, there is an error when we run the training code with "python tools/train.py configs/solo/solo_r50_fpn_8gpu_1x.py".  The error information is as follows:

2020-07-16 06:36:09,661 - mmdet - INFO - Start running, host: jhvision-3@jhvision-3, work_dir: /home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/work_dirs/solo_release_r50_fpn_8gpu_1x
2020-07-16 06:36:09,661 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
/home/jhvision-3/anaconda3/envs/SOLO_master/lib/python3.6/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/mmdet/apis/train.py", line 111, in train_detector
    timestamp=timestamp)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/mmdet/apis/train.py", line 297, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/mmcv-0.2.16/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/mmcv-0.2.16/mmcv/runner/runner.py", line 268, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/mmdet/apis/train.py", line 78, in batch_processor
    losses = model(**data)
  File "/home/jhvision-3/anaconda3/envs/SOLO_master/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jhvision-3/anaconda3/envs/SOLO_master/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jhvision-3/anaconda3/envs/SOLO_master/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/mmdet/models/detectors/base.py", line 142, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/mmdet/models/detectors/single_stage_ins.py", line 78, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/jhvision-3/qiqi/SHUmath/Ding/code/SOLO/SOLO-master/mmdet/models/anchor_heads/solo_head.py", line 203, in loss
    num_ins = flatten_ins_ind_labels.sum()
RuntimeError: "sum_cuda" not implemented for 'Bool'

**Comment by WXinlong** [comment]
@Womcos  Please refer to #24 .
