### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by keshavoct98** [WXinlong/SOLO#74]
I am getting runtime error while running setup.py.
My environment details:
gpu - GTX 1660
python - 3.7.7
cuda - 10.2
pytorch - 1.5.1
gcc - 7.5.0
ubuntu 18.04

Error info:-

/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:1: note: declared here
       DeprecatedTypeProperties & type() const {
     ^ ~~
    /home/keshavoct98/SOLO/mmdet/ops/nms/src/nms_kernel.cu:86:50: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
       scalar_t* boxes_dev = boxes_sorted.data<scalar_t>();
                                                      ^
    /home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:341:1: note: declared here
       T * data() const {
     ^ ~~
    /home/keshavoct98/SOLO/mmdet/ops/nms/src/nms_kernel.cu:117:46: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
       int64_t* keep_out = keep.data<int64_t>();
                                                  ^
    /home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:341:1: note: declared here
       T * data() const {
     ^ ~~
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1423, in _run_ninja_build
        check=True)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/keshavoct98/SOLO/setup.py", line 301, in <module>
        zip_safe=False)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
        build_ext.build_extensions(self)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 437, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/keshavoct98/anaconda3/envs/torch/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/keshavoct98/SOLO/setup.py'"'"'; __file__='"'"'/home/keshavoct98/SOLO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 790, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/keshavoct98/anaconda3/envs/torch/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/keshavoct98/anaconda3/envs/torch/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/keshavoct98/SOLO/setup.py'"'"'; __file__='"'"'/home/keshavoct98/SOLO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-ma_et4vh'

**Comment by keshavoct98** [comment]
Downgrading pytorch and torchvision to 1.4.0 and 0.5.0 solved the error.

**Comment by Euphoria16** [comment]
I met the same problem and solved it by downgrading pytorch to 1.5.0 and cudatoolkit to 10.1.
