### ISSUE TITLE
solov2 config error: RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by Womcos** [WXinlong/SOLO#78]
We implement the latest code SOLO_v2 for training and get one error. We follow the installation and dataset preparation process for coco dataset. Our environments are as bellows:
GPU: RTX 2080 Ti
python: 3.6
cuda: 9.0
mmcv: 0.2.16
pytorch: 1.1.0
We can regularly run the training and test process with the solov1 config: python tools/train.py configs/solo/solo_r50_fpn_8gpu_1x.py. However, there is an error when we try to run the training code with the solov2 config: python tools/train.py configs/solov2/solov2_r50_fpn_8gpu_1x.py.
The error is as follow:
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/home/dxf/code/SOLO/SOLO-master/mmdet/apis/train.py", line 111, in train_detector
    timestamp=timestamp)
  File "/home/dxf/code/SOLO/SOLO-master/mmdet/apis/train.py", line 297, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/dxf/code/SOLO/mmcv-0.2.16/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dxf/code/SOLO/mmcv-0.2.16/mmcv/runner/runner.py", line 275, in train
    self.call_hook('after_train_iter')
  File "/home/dxf/code/SOLO/mmcv-0.2.16/mmcv/runner/runner.py", line 231, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/dxf/code/SOLO/mmcv-0.2.16/mmcv/runner/hooks/optimizer.py", line 18, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/dxf/anaconda3/envs/SOLO/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/dxf/anaconda3/envs/SOLO/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: invalid argument

**Comment by zhangyunming** [comment]
hi， have you solve it？ i met the same error.

**Comment by Womcos** [comment]
The problem is soloved by updating the cuda version from 9.0 to 10.0.

**Comment by zhangyunming** [comment]
ok
thanks so much
